if (!requireNamespace("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("DESeq2")
library (DESeq2)
counts <- read.table("allconditionscountfile.txt", header=TRUE, sep="\t", row.names=1)
sampleInfo <- read.csv("design_file.csv")
head (counts)
head (sampleInfo)
nrow (counts)
dds <- DESeqDataSetFromMatrix(countData=counts, colData=sampleInfo, design= ~ condition)
dds <- DESeq(dds)
res <- results(dds, c("condition","condition1","condition2"))
res
write.csv(res, file="DEGlist.csv")